# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4v16lzoOHkB-_RuvzuTjb4Gd_tMn6bR
"""

CALCULAR AREA DEL RECTANGULO

def calcular_area(base, altura):
    return base * altura

b = int(input('Ingrese la base del rectangulo: '))
a = int(input('Ingrese la altura del rectangulo: '))
area = calcular_area(b,a)
print(f'el area del rectangulo es:{area}')